// Prepares the site of the language (site/) before “kaury build”:
// - the reference, generated from the vocabulary of the compiler (one source of truth);
// - the playground (its built bundles) under /play/;
// - the files AI assistants read first: kaury-ai.md, llms.txt, llms-full.txt, a .md twin of every docs page.
// Run: npx tsx scripts/site-prepare.ts   (after “npm run build”, which makes the playground bundles)

import { readFileSync, writeFileSync, mkdirSync, cpSync, readdirSync, rmSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { stringify, parse } from 'yaml'
import { ELEMENTS, STYLES, ELEMENT_OPTIONS, UNIVERSAL_OPTIONS, MOTIONS, LIGHTS, CAMERAS, TRANSITIONS } from '../src/core/vocabulary.js'
import { KAURY_FUNCTIONS, KAURY_VALUES } from '../src/core/globals.js'
import { allKeywords, aliasesOf } from '../src/core/keywords.js'
import { compile } from '../src/core/index.js'
import { buildLibrary } from './library.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const site = join(root, 'site')
const pub = join(site, 'public')
const URL = 'https://kaury.dev'
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

// ---------------- reference ----------------
const fr = (a: string[] = []) => a.filter((x) => /^[a-zà-ÿ-]+$/.test(x)).join(', ')
const reference = {
  version: pkg.version,
  elements: Object.entries(ELEMENTS).map(([name, e]) => ({
    name, kind: e.kind, tag: e.tag, help: e.help, example: e.example,
    options: Object.keys(ELEMENT_OPTIONS[name] ?? {}).join(', '),
    french: fr(aliasesOf(name)),
  })),
  styles: Object.entries(STYLES).map(([name, s]) => ({ name, help: s.help, example: s.example, values: (s.words ?? []).join(' | '), french: fr(s.aliases) })),
  universal: Object.entries(UNIVERSAL_OPTIONS).map(([name, s]) => ({ name, help: s.help, example: s.example })),
  motions: Object.entries(MOTIONS).map(([name, s]) => ({ name: name.replace('-', ' '), help: s.help, example: s.example })),
  functions: Object.entries(KAURY_FUNCTIONS).map(([name, f]) => ({ name, help: f.help, french: fr(f.aliases) })),
  values: Object.entries(KAURY_VALUES).map(([name, f]) => ({ name, help: f.help })),
  keywords: allKeywords().filter((k) => !(k in ELEMENTS)).map((k) => ({ name: k, french: fr(aliasesOf(k)) })).filter((k) => k.french),
  lights: LIGHTS.join(', '),
  cameras: CAMERAS.map((c) => c.replace('-', ' ')).join(', '),
  transitions: TRANSITIONS.join(', '),
  particles: 'stars, snow, bubbles, dust, confetti',
}
mkdirSync(join(site, 'content'), { recursive: true })
writeFileSync(join(site, 'content', 'reference.yaml'), '# Generated by scripts/site-prepare.ts from src/core — do not edit.\n' + stringify(reference, { lineWidth: 0 }))
writeFileSync(join(site, 'content', 'release.yaml'), `# Generated by scripts/site-prepare.ts — do not edit.
version: "${pkg.version}"
`)

// ---------------- playground ----------------
const play = join(pub, 'play')
rmSync(play, { recursive: true, force: true })
mkdirSync(play, { recursive: true })
for (const f of ['index.html', 'kaury-compiler.js', 'star.svg']) cpSync(join(root, 'playground', f), join(play, f))
cpSync(join(root, 'playground', 'rt'), join(play, 'rt'), { recursive: true })
// the playground page itself is /playground (written in Kaury); /play/ is the app inside it
writeFileSync(join(play, 'index.html'), readFileSync(join(play, 'index.html'), 'utf8')
  .replace('<head>', '<head>\n<meta name="robots" content="noindex">\n<link rel="canonical" href="' + URL + '/playground/">'))

// ---------------- live examples of the home page ----------------
// real .kaury files, compiled here: an example that does not compile stops the build
const TITLES: Record<string, [string, string]> = {
  reactive: ['Reactive', 'A state changes, the page follows. No hooks, no listeners.'],
  immersive: ['3D', 'A scene, a light, an object that follows the mouse. Three.js loads by itself.'],
  data: ['Data', 'Lists, loops, a cart and a price format, in plain words.'],
  form: ['Forms', 'Each field is bound to a state. Validation is built in.'],
}
const exDir = join(site, 'examples')
const examples = readdirSync(exDir).filter((f) => f.endsWith('.kaury')).sort().map((f) => {
  const code = readFileSync(join(exDir, f), 'utf8').trim()
  const r = compile(code, { file: f })
  if (!r.ok) throw new Error(`site/examples/${f} does not compile:\n` + r.errors.map((e) => e.format(code)).join('\n'))
  const id = f.replace(/^\d+-|\.kaury$/g, '')
  const hash = Buffer.from(code, 'utf8').toString('base64')
  return { id, name: TITLES[id]?.[0] ?? id, caption: TITLES[id]?.[1] ?? '', lines: code.split('\n').length, code: '```kaury\n' + code + '\n```', preview: `/play/?embed#${hash}`, edit: `/play/#${hash}` }
})
writeFileSync(join(site, 'content', 'examples.yaml'), '# Generated by scripts/site-prepare.ts from site/examples — do not edit.\n' + stringify({ list: examples }, { lineWidth: 0 }))

// ---------------- files for AI assistants ----------------
const spec = readFileSync(join(root, 'docs', 'kaury-ai.md'), 'utf8')
cpSync(join(root, 'docs', 'kaury-ai.md'), join(pub, 'kaury-ai.md'))

interface Doc { slug: string; title: string; description: string; order: number; group: string; body: string }
const docsDir = join(site, 'content', 'docs')
const docs: Doc[] = readdirSync(docsDir).filter((f) => f.endsWith('.md')).map((f) => {
  const text = readFileSync(join(docsDir, f), 'utf8').replace(/\r\n?/g, '\n')
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/)
  const meta = parse(m?.[1] ?? '') ?? {}
  return { slug: f.replace(/\.md$/, ''), body: (m?.[2] ?? text).trim(), ...meta }
}).sort((a, b) => a.order - b.order)

// a Markdown twin of every docs page: /docs/getting-started.md next to /docs/getting-started/
mkdirSync(join(pub, 'docs'), { recursive: true })
for (const d of docs) writeFileSync(join(pub, 'docs', d.slug + '.md'), `# ${d.title}\n\n> ${d.description}\n\n${d.body}\n`)

// the blog: the same twins, newest first
interface Post { slug: string; title: string; description: string; date: string; body: string }
const blogDir = join(site, 'content', 'blog')
const posts: Post[] = readdirSync(blogDir).filter((f) => f.endsWith('.md')).map((f) => {
  const text = readFileSync(join(blogDir, f), 'utf8').replace(/\r\n?/g, '\n')
  const m = text.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/)
  const meta = parse(m?.[1] ?? '') ?? {}
  return { slug: f.replace(/\.md$/, ''), body: (m?.[2] ?? text).trim(), ...meta, date: String(meta.date ?? '') }
}).sort((a, b) => b.date.localeCompare(a.date))
mkdirSync(join(pub, 'blog'), { recursive: true })
for (const b of posts) writeFileSync(join(pub, 'blog', b.slug + '.md'), `# ${b.title}\n\n> ${b.description}\n\n${b.body}\n`)

const intro = `Kaury is an open-source programming language (MIT) that compiles a single .kaury file into a complete, fast website: logic, structure, style and 3D in the same file. Pages are rendered on the server, score 100 on all four Lighthouse categories, and 3D (Three.js) is one line of code. Keywords are English, with French aliases.`
const llms = `# Kaury

> ${intro}

Install: \`npm install -g @kaury/cli\`, then \`kaury new my-site\`, \`kaury dev\`, \`kaury build\`.
To write Kaury, an AI assistant should read the specification first: it is complete, short and made for that.

## Specification for AI assistants

- [kaury-ai.md](${URL}/kaury-ai.md): the whole language in one file — syntax, core, web, immersion, golden rules, a complete example

## Docs

${docs.map((d) => `- [${d.title}](${URL}/docs/${d.slug}.md): ${d.description}`).join('\n')}

## Tutorials

${posts.map((b) => `- [${b.title}](${URL}/blog/${b.slug}.md): ${b.description}`).join('\n')}

## More

- [Reference](${URL}/reference/): every element, option, motion and function, generated from the compiler
- [Playground](${URL}/playground/): write Kaury, see the site, nothing to install
- [Source code](https://github.com/theoblondel/kaury-lang): compiler, runtime, CLI, VS Code extension (MIT)
- [Full text for LLMs](${URL}/llms-full.txt): this index, the specification and every docs page in one file
`
writeFileSync(join(pub, 'llms.txt'), llms)
writeFileSync(join(pub, 'llms-full.txt'), `# Kaury — full documentation for LLMs\n\n> ${intro}\n\nSource: ${URL} · https://github.com/theoblondel/kaury-lang · version ${pkg.version}\n\n---\n\n${spec.trim()}\n\n${[...docs.map((d) => ({ ...d, dir: 'docs' })), ...posts.map((b) => ({ ...b, dir: 'blog' }))].map((d) => `---\n\n# ${d.title}\n\nURL: ${URL}/${d.dir}/${d.slug}/\n\n${d.body}`).join('\n\n')}\n`)

// Agentic Resource Discovery (ARD 1.0): AI agents find the skill "write Kaury" by themselves
// https://agenticresourcediscovery.org/spec/ — announced in every page (<link rel="ai-catalog">; an Agentmap line in robots.txt is not yet understood by robots.txt validators)
const catalog = {
  specVersion: '1.0',
  host: { displayName: 'Kaury', documentationUrl: `${URL}/docs/`, logoUrl: `${URL}/mark.svg` },
  entries: [
    {
      identifier: 'urn:air:kaury.dev:skills:write-kaury',
      displayName: 'Write Kaury websites',
      type: 'text/markdown; profile="urn:air:agent-skills"',
      url: `${URL}/kaury-ai.md`,
      description: 'The complete specification of the Kaury language, written for AI assistants: read it, then write a whole website (pages, styles, animations, 3D) in one .kaury file and check it with "kaury check --json".',
      tags: ['kaury', 'web', 'website', 'programming language', '3d', 'seo'],
      capabilities: ['WriteKauryWebsite', 'FixKauryErrors', 'Kaury3DScene'],
      representativeQueries: [
        'Write a website in Kaury',
        'How do I add a 3D object to a Kaury page?',
        'Fix the errors of my site.kaury file',
        'Make a landing page with a contact form in one file',
        'Which language builds immersive websites with Lighthouse 100?',
      ],
    },
    {
      identifier: 'urn:air:kaury.dev:docs:llms-full',
      displayName: 'Kaury documentation for LLMs',
      type: 'text/markdown; profile="urn:air:agent-skills"',
      url: `${URL}/llms-full.txt`,
      description: 'The specification, every docs page and every tutorial in one Markdown file.',
      tags: ['kaury', 'documentation'],
      representativeQueries: ['Kaury documentation', 'Kaury tutorial'],
    },
  ],
}
mkdirSync(join(pub, '.well-known'), { recursive: true })
writeFileSync(join(pub, '.well-known', 'ai-catalog.json'), JSON.stringify(catalog, null, 2) + '\n')

// AI crawlers are welcome: being read and quoted is the point of this site
writeFileSync(join(pub, 'robots.txt'), `User-agent: *\nAllow: /\nDisallow: /play/\nDisallow: /lib/\n\n# AI assistants and their crawlers are welcome: start with /llms.txt\nUser-agent: GPTBot\nAllow: /\nUser-agent: OAI-SearchBot\nAllow: /\nUser-agent: ChatGPT-User\nAllow: /\nUser-agent: ClaudeBot\nAllow: /\nUser-agent: Claude-User\nAllow: /\nUser-agent: Claude-SearchBot\nAllow: /\nUser-agent: PerplexityBot\nAllow: /\nUser-agent: Google-Extended\nAllow: /\nUser-agent: Applebot-Extended\nAllow: /\n\nSitemap: ${URL}/sitemap.xml\n`)

// ---------------- library: ready-made pieces and homepages, each built into its own preview ----------------
const library = await buildLibrary(root, site)

console.log(`site prepared: ${reference.elements.length} elements, ${reference.styles.length} styles, ${docs.length} docs pages, ${posts.length} posts, ${examples.length} examples, ${library.pieces} library pieces (${library.built} built)`)
